### ISSUE TITLE
build/restore error with nuget feed

### ISSUE THREAD

**Issue by lookitskris** [Microsoft/TailwindTraders-Desktop#2]
I did a clean clone of the source, and tried to do a dotnet restore which produced the following error 

`C:\Program Files\dotnet\sdk\3.0.100-preview-009812\NuGet.targets(114,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/tailwindtraders/_packaging/Toolkit/nuget/v3/index.json. [c:\TailwindTraders-Desktop\Source\couponreader.sln]
C:\Program Files\dotnet\sdk\3.0.100-preview-009812\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [c:\TailwindTraders-Desktop\Source\couponreader.sln]`

I havent delved into the source code too much, but i noticed the nuget.config contains this

`<add key="toolkit" value="https://pkgs.dev.azure.com/tailwindtraders/_packaging/Toolkit/nuget/v3/index.json" />`

visiting that link asks me to sign in, and when I do it says I am unauthorized

Something i'm missing here?

**Comment by eiximenis** [comment]
Hi @lookitskris 
I have updated the nuget source (commit 2452732270eb97f25e5bac5bb7a6430a08824962). It should compile now.

I close the issue, feel free to reopen it if still having package restore errors.
