### ISSUE TITLE
Unable to open the project in VS2017, project file is incomplete. Expected imports are missing.

### ISSUE THREAD

**Issue by Portelinha** [Microsoft/TailwindTraders-Desktop#3]
Opening the soluntion in VS 2017 gives the following errors:

> 
> CouponReader.Core.Wpf\CouponReader.Core.Wpf.csproj : error  : Project file is incomplete. Expected imports are missing.
> CouponReader.Core.Common\CouponReader.Core.Common.csproj : error  : Project file is incomplete. Expected imports are missing.

Visual Studio 2017 installed (v 15.9.3)
-.Net Core SDK 2.1.5, 2.2.1 and 3.0.100
-CLI 2.0 Azure
-Framework 4.7.2 SDK

Please, can anyone help?

**Comment by rido-min** [comment]
Hi @Portelinha,

While .NET Core 3 is in preview you must use a Visual Studio preview version, please see [this blog post](https://blogs.msdn.microsoft.com/dotnet/2018/11/13/net-core-tooling-update-for-visual-studio-2017-version-15-9/) for more details.

You can get Visual Studio 2019 Preview from [https://visualstudio.microsoft.com/vs/preview](https://visualstudio.microsoft.com/vs/preview)
