### ISSUE TITLE
Will this run on MacOS and/or Linux

### ISSUE THREAD

**Issue by Sohojoe** [Microsoft/TailwindTraders-Desktop#4]
Hi there,

We are trying to understand how we would use the TailwindTraders cross-platform model on MacOS and Linux - as WPF will now target .NetCore 3.0 - does this mean WPF is the way to go for MacOS and Linux?

thanks!

**Comment by rido-min** [comment]
Hi @Sohojoe 

WPF and WinForms on .NET Core 3 will work only on Windows. Currently there are no plans to support MacOS and Linux.
